StudentApp/Controllers/FakultetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EF;

namespace StudentApp.Controllers
{
    public class FakultetsController : Controller
    {
        private StudentAppEntities db = new StudentAppEntities();

        // GET: Fakultets
        public ActionResult Index()
        {
            return View(db.Fakultet.ToList());
        }

        // GET: Fakultets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fakultet fakultet = db.Fakultet.Find(id);
            if (fakultet == null)
            {
                return HttpNotFound();
            }
            return View(fakultet);
        }

        // GET: Fakultets/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Fakultets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FakultetId,Naziv,OIB,Adresa")] Fakultet fakultet)
        {
            if (ModelState.IsValid)
            {
                db.Fakultet.Add(fakultet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(fakultet);
        }

        // GET: Fakultets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fakultet fakultet = db.Fakultet.Find(id);
            if (fakultet == null)
            {
                return HttpNotFound();
            }
            return View(fakultet);
        }

        // POST: Fakultets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FakultetId,Naziv,OIB,Adresa")] Fakultet fakultet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fakultet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fakultet);
        }

        // GET: Fakultets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fakultet fakultet = db.Fakultet.Find(id);
            if (fakultet == null)
            {
                return HttpNotFound();
            }
            return View(fakultet);
        }

        // POST: Fakultets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Fakultet fakultet = db.Fakultet.Find(id);
            db.Fakultet.Remove(fakultet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentApp/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EF;

namespace StudentApp.Controllers
{
    public class StudentsController : Controller
    {
        private StudentAppEntities db = new StudentAppEntities();

        // GET: Students
        public ActionResult Index()
        {
            var student = db.Student.Include(s => s.Fakultet);
            return View(student.ToList());
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Student.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            ViewBag.FakultetId = new SelectList(db.Fakultet, "FakultetId", "Naziv");
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentId,Ime,Prezime,JMBAG,FakultetId")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Student.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FakultetId = new SelectList(db.Fakultet, "FakultetId", "Naziv", student.FakultetId);
            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Student.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            ViewBag.FakultetId = new SelectList(db.Fakultet, "FakultetId", "Naziv", student.FakultetId);
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentId,Ime,Prezime,JMBAG,FakultetId")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FakultetId = new SelectList(db.Fakultet, "FakultetId", "Naziv", student.FakultetId);
            return View(student);
        }

        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Student.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Student.Find(id);
            db.Student.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentApp/Views/Students/Create.cshtml
@model EF.Student

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JMBAG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JMBAG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JMBAG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FakultetId, "FakultetId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FakultetId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FakultetId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentApp/Views/Students/Delete.cshtml
@model EF.Student

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JMBAG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JMBAG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fakultet.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fakultet.Naziv)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StudentApp/Views/Students/Details.cshtml
@model EF.Student

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JMBAG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JMBAG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fakultet.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fakultet.Naziv)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StudentId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StudentApp/Views/Students/Edit.cshtml
@model EF.Student

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentId)

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JMBAG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JMBAG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JMBAG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FakultetId, "FakultetId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FakultetId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FakultetId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentApp/Views/Students/Index.cshtml
@model IEnumerable<EF.Student>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Dodaj studenta", "Create")
</p>
<div class="col-sm-8">
    <input type="text" class="form-control" placeholder="Search">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JMBAG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fakultet.Naziv)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prezime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JMBAG)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fakultet.Naziv)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.StudentId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.StudentId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.StudentId })
                </td>
            </tr>
        }
    </table>
    <p id="demo"></p>
</div>
<div class="col-sm-4"><img class="img-responsive" src="~/Content/Slike/fakultet1.jpg"</div>
    <p>
        @Html.ActionLink("Dodaj novi fakultet", "Create", "Fakultets")
    </p>